import type { ExternalRunnerPort, RunnerDispatchContext, RunnerDispatchInput, RunnerDispatchResult } from "../../core/run/runnerPort.js";

export class ManualExternalRunner implements ExternalRunnerPort {
  async dispatch(input: RunnerDispatchInput, context: RunnerDispatchContext): Promise<RunnerDispatchResult> {
    return {
      runnerName: "manual-external-v0",
      state: "accepted",
      message: `Prepared manual external handoff for task "${input.task.title}".`,
      promptDraft: {
        content: buildPrompt(input, context),
      },
    };
  }
}

function buildPrompt(input: RunnerDispatchInput, context: RunnerDispatchContext): string {
  const details = input.task.details;
  const acceptanceCriteria =
    input.task.acceptanceCriteria.length === 0
      ? "- None recorded"
      : input.task.acceptanceCriteria.map((criterion) => `- ${criterion}`).join("\n");
  const taskDetails = details
    ? `## Structured task\n\nGoal: ${details.goal}\nInput: ${details.input}\nAction: ${details.action}\nOutput: ${details.output}\nValidation: ${details.validation}\n`
    : "";

  return `# Cuer Task Handoff

Project: ${input.project.name}
Project root: ${context.projectRoot}
Plan id: ${input.plan.id}
Task id: ${input.task.id}
Task type: ${input.task.type}
Priority: ${input.task.priority}

## Goal

${input.plan.goal}

## Task

${input.task.title}

${input.task.description}

${taskDetails}
## Acceptance criteria

${acceptanceCriteria}

## Workspace notes

- Use the current repository at ${context.projectRoot}
- Persist any generated artifacts under ${context.artifactsDir} when relevant
- Keep execution logs local under ${context.logsDir}
- This handoff was generated by Cuer's manual external runner, so execution status must be reported back explicitly in a future workflow
`;
}
